# Generated by Django 4.0.5 on 2022-06-22 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controleGas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='data',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data'),
        ),
    ]
