# Generated by Django 4.0.5 on 2022-06-22 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controleGas', '0002_alter_leitura_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='data',
            field=models.DateField(auto_now_add=True, verbose_name='Criado'),
        ),
    ]
