# Generated by Django 4.0.5 on 2022-06-22 20:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_controleGas', '0003_alter_leitura_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leitura',
            name='data',
            field=models.DateTimeField(default=datetime.date, verbose_name='Data'),
        ),
    ]
